# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
print(torch.__version__)
# Create random tensor
random_tensor=torch.rand(7,7)
random_tensor

2.8.0+cu126


tensor([[0.8735, 0.0526, 0.1488, 0.7060, 0.5262, 0.6805, 0.9845],
        [0.7572, 0.5702, 0.6441, 0.2844, 0.3978, 0.1781, 0.8488],
        [0.7325, 0.7186, 0.2449, 0.4572, 0.5860, 0.3485, 0.4275],
        [0.7631, 0.0430, 0.7483, 0.0105, 0.3481, 0.5575, 0.3898],
        [0.9202, 0.6360, 0.9481, 0.1355, 0.7721, 0.5134, 0.9710],
        [0.2709, 0.5037, 0.9197, 0.8494, 0.5466, 0.8058, 0.3657],
        [0.7805, 0.4900, 0.8511, 0.2958, 0.0613, 0.9749, 0.9234]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
random_tensor1=torch.rand(1,7)

# Perform matrix multiplication
# if we multiply random_tensor1* random_tensor we don't need to transpose of random_tensor because number of columns in the first=the number of rows in the second
torch.matmul(random_tensor1,random_tensor)

# we need the transpose here
random_tensor1_transpose= random_tensor1.T
print("the output")
torch.matmul(random_tensor,random_tensor1_transpose)

the output


tensor([[2.4415],
        [2.1379],
        [1.9555],
        [2.5698],
        [2.2111],
        [3.3916],
        [2.1413]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand_tensor2=torch.rand(7,4)
rand_tensor3=torch.rand(4,1)

# Matrix multiply tensors
output=torch.matmul(rand_tensor2,rand_tensor3)
output,output.shape

(tensor([[0.5288],
         [1.2787],
         [0.8014],
         [0.6401],
         [0.7402],
         [1.4039],
         [0.6085]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [3]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.cuda.manual_seed(1234)
# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
device="cuda" if torch.cuda.is_available() else "cpu"
random_tensor4=torch.rand(2,3)
random_tensor5=torch.rand(2,3)
random_tensor4_to_gpu=random_tensor4.to(device)
random_tensor5_to_gpu=random_tensor5.to(device)
print("Device:",device)
print(random_tensor4_to_gpu)
print(random_tensor5_to_gpu)



Device: cuda
tensor([[0.0643, 0.6847, 0.2345],
        [0.1500, 0.6246, 0.9223]], device='cuda:0')
tensor([[0.2084, 0.8423, 0.1021],
        [0.4966, 0.8934, 0.3538]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
tensor_A=random_tensor4
tensor_B=random_tensor5
tensor_B_transpose=tensor_B.T
output_1=torch.mm(tensor_A,tensor_B_transpose)
output_1_to_gpu=output_1.to(device)
print(output_1_to_gpu," , ",output_1_to_gpu.shape)


tensor([[0.6141, 0.7266],
        [0.6515, 0.9588]], device='cuda:0')  ,  torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [25]:
# Find max
maximum=output_1.max().item()
print("Maximum =",maximum,"-->",(output_1.max()))
# Find min
minimum=output_1.min().item()
print("minimum =",minimum,"-->",(output_1.min()))

Maximum = 0.9587976932525635 --> tensor(0.9588)
minimum = 0.6140502095222473 --> tensor(0.6141)


### 9. Find the maximum and minimum index values of the output of 7.

In [32]:
# Find arg max
print("the maximum index value of the output =",output_1.argmax().item())

# Find arg min
print("the minumum index value of the output =",output_1.argmin().item())

the maximum index value of the output = 3
the minumum index value of the output = 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [33]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_c=torch.rand(1,1,1,10)

# Remove single dimensions
tensor_c_squeezed=tensor_c.squeeze()

# Print out tensors and their shapes
print(tensor_c,tensor_c.shape)

print(tensor_c_squeezed,tensor_c_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
